from src.registry import PROMPT
from src.prompt.types import Prompt
from typing import Any, Dict, Literal
from pydantic import Field, ConfigDict

# ---------------------GRPO Reflection Prompt---------------------

GRPO_OPTIMIZER_REFLECTION_AGENT_PROFILE = """
You are an expert at analyzing candidate solutions and their RL metrics to identify which variables (prompts, tools, solutions, etc.) need improvement for GRPO optimization.
"""

GRPO_OPTIMIZER_REFLECTION_INTRODUCTION = """
<intro>
You excel at:
- Analyzing multiple candidate solutions generated by GRPO
- Understanding reward, advantage, policy ratio, and objective metrics
- Identifying patterns across candidate solutions to guide optimization
- Making strategic decisions about variable improvements based on RL signals
- Providing specific, actionable feedback based on GRPO optimization principles
</intro>
"""

GRPO_OPTIMIZER_REFLECTION_REASONING_RULES = """
<reasoning_rules>
**GRPO Metrics Interpretation:**
- **Reward (0.0-1.0)**: Task completion quality for each candidate
- **Advantage**: Normalized reward advantage across candidates
- **Policy Ratio**: Similarity to reference solution (lower = more different)
- **Objective**: GRPO optimization objective (higher = better)

Based on the current solution and candidate solutions with their RL metrics, analyze:

IMPORTANT: You can ONLY analyze and suggest improvements for variables that are listed in <current_variables>. 
Do NOT suggest creating new variables or tools that don't exist. Work with what is provided.

Please analyze the execution result and the provided variables in <current_variables>, then provide:
- **What went wrong or could be improved**
   - Identify specific issues in the agent's behavior or output
   - Note any errors, inefficiencies, or suboptimal outcomes

- **Which variables (from current_variables) contributed to these issues?**
   - Analyze prompt variables (system_prompt, agent_message_prompt and their sub-variables): identify unclear instructions, missing context, or structural issues
   - Analyze tool variables (tool_code): identify bugs, missing functionality, or incorrect logic
   - Analyze solution variables: identify if the solution approach itself needs improvement
   - Determine which specific variable(s) from <current_variables> are most likely causing the problems

- **Specific recommendations for improving each problematic variable**
   - You MUST only recommend improvements for variables that exist in <current_variables>
   - For prompt variables: provide concrete suggestions for clearer instructions, better structure, or additional context. When improving prompts intended for problem-solving, consider phrasing that activates the model's reasoning.
   - For tool variables: provide specific code fixes, feature additions, or logic corrections
   - For solution variables: suggest alternative approaches or improvements to the solution strategy, ensuring the format meets task requirements and can be correctly parsed
   - Focus on making each variable type more effective for the given task
</reasoning_rules>
"""

GRPO_OPTIMIZER_REFLECTION_OUTPUT = """
<output>
Please ONLY respond with the text of the analysis and recommendations, without any additional commentary or explanation.
</output>
"""

GRPO_OPTIMIZER_REFLECTION_SYSTEM_PROMPT_TEMPLATE = """
{{ agent_profile }}
{{ introduction }}
{{ reasoning_rules }}
{{ output }}
"""

GRPO_OPTIMIZER_REFLECTION_AGENT_MESSAGE_PROMPT_TEMPLATE = """
{{ task }}
{{ current_variables }}
{{ execution_result }}

**Candidate Solutions Analysis:**
{{ candidate_solutions }}
"""

GRPO_OPTIMIZER_REFLECTION_SYSTEM_PROMPT = {
    "name": "grpo_optimizer_reflection_system_prompt",
    "type": "system_prompt",
    "description": "System prompt for GRPO reflection optimizer",
    "template": GRPO_OPTIMIZER_REFLECTION_SYSTEM_PROMPT_TEMPLATE,
    "variables": {
        "agent_profile": {
            "name": "agent_profile",
            "type": "system_prompt",
            "description": "Describes the agent's GRPO expertise.",
            "require_grad": False,
            "template": None,
            "variables": GRPO_OPTIMIZER_REFLECTION_AGENT_PROFILE
        },
        "introduction": {
            "name": "introduction",
            "type": "system_prompt",
            "description": "Defines GRPO-based optimization capabilities.",
            "require_grad": False,
            "template": None,
            "variables": GRPO_OPTIMIZER_REFLECTION_INTRODUCTION
        },
        "reasoning_rules": {
            "name": "reasoning_rules",
            "type": "system_prompt",
            "description": "Defines how to analyze GRPO candidates and metrics.",
            "require_grad": False,
            "template": None,
            "variables": GRPO_OPTIMIZER_REFLECTION_REASONING_RULES
        },
        "output": {
            "name": "output",
            "type": "system_prompt",
            "description": "Defines the output format for GRPO analysis.",
            "require_grad": False,
            "template": None,
            "variables": GRPO_OPTIMIZER_REFLECTION_OUTPUT
        }
    }
}

GRPO_OPTIMIZER_REFLECTION_AGENT_MESSAGE_PROMPT = {
    "name": "grpo_optimizer_reflection_agent_message_prompt",
    "type": "agent_message_prompt",
    "description": "Agent message for GRPO reflection optimizer",
    "require_grad": False,
    "template": GRPO_OPTIMIZER_REFLECTION_AGENT_MESSAGE_PROMPT_TEMPLATE,
    "variables": {
        "task": {
            "name": "task",
            "type": "agent_message_prompt",
            "description": "Describes the task to be executed.",
            "require_grad": False,
            "template": None,
            "variables": None
        },
        "current_variables": {
            "name": "current_variables",
            "type": "agent_message_prompt",
            "description": "Describes the current variables.",
            "require_grad": False,
            "template": None,
            "variables": None
        },
        "execution_result": {
            "name": "execution_result",
            "type": "agent_message_prompt",
            "description": "Describes the agent execution result.",
            "require_grad": False,
            "template": None,
            "variables": None
        },
        "candidate_solutions": {
            "name": "candidate_solutions",
            "type": "agent_message_prompt",
            "description": "Analysis of candidate solutions and their RL metrics.",
            "require_grad": False,
            "template": None,
            "variables": None
        }
    }
}

@PROMPT.register_module(force=True)
class GrpoOptimizerReflectionSystemPrompt(Prompt):
    """System prompt template for GRPO reflection optimizer."""
    model_config = ConfigDict(arbitrary_types_allowed=True, extra="allow")

    type: str = Field(default='system_prompt', description="The type of the prompt")
    name: str = Field(default="grpo_optimizer_reflection", description="The name of the prompt")
    description: str = Field(default="System prompt for GRPO reflection optimizer", description="The description of the prompt")
    metadata: Dict[str, Any] = Field(default={}, description="The metadata of the prompt")

    prompt_config: Dict[str, Any] = Field(default=GRPO_OPTIMIZER_REFLECTION_SYSTEM_PROMPT, description="System prompt information")

@PROMPT.register_module(force=True)
class GrpoOptimizerReflectionAgentMessagePrompt(Prompt):
    """Agent message prompt template for GRPO reflection optimizer."""
    model_config = ConfigDict(arbitrary_types_allowed=True, extra="allow")

    type: str = Field(default='agent_message_prompt', description="The type of the prompt")
    name: str = Field(default="grpo_optimizer_reflection", description="The name of the prompt")
    description: str = Field(default="Agent message prompt for GRPO reflection optimizer", description="The description of the prompt")
    metadata: Dict[str, Any] = Field(default={}, description="The metadata of the prompt")

    prompt_config: Dict[str, Any] = Field(default=GRPO_OPTIMIZER_REFLECTION_AGENT_MESSAGE_PROMPT, description="Agent message prompt information")

# ---------------------GRPO Improvement Prompt---------------------

GRPO_OPTIMIZER_IMPROVEMENT_AGENT_PROFILE = """
You are an expert at improving variables (prompts, tools, solutions) based on feedback and analysis.
"""

GRPO_OPTIMIZER_IMPROVEMENT_INTRODUCTION = """
<intro>
You excel at:
- Improving ONLY the variables provided in <current_variables> based on feedback and analysis
- Keeping the core purpose and structure of the original variable
- Addressing all identified issues specific to each variable type
- Making improvements appropriate for the variable type (clearer instructions for prompts, bug fixes for tools, better strategies for solutions)
- Removing unnecessary or problematic elements
- Adding missing elements that would help the agent perform better

IMPORTANT: You can ONLY improve variables that are listed in <current_variables>. 
Do NOT suggest or create new variables that don't exist in the provided list.
</intro>
"""

GRPO_OPTIMIZER_IMPROVEMENT_REASONING_RULES = """
<reasoning_rules>
Based on the analysis and feedback provided, please improve the variable by:

1. **Keep the core purpose and structure**
   - Maintain the original variable's fundamental purpose
   - Preserve the overall structure unless it's part of the problem

2. **Address all identified issues**
   - Systematically address each issue mentioned in the analysis
   - Ensure no problems are left unresolved

3. **Make improvements appropriate for the variable type**
   - For prompt variables: Make instructions clearer and more specific, replace vague language with precise instructions, add concrete examples, clarify ambiguous requirements
   - For tool variables: Fix bugs, correct logic errors, add missing functionality, improve error handling
   - For solution variables: Suggest better approaches, improve strategy, refine the solution method

4. **Better organization**
   - For prompts: Improve the logical flow of instructions, group related concepts together, use clear headings and structure
   - For tools: Organize code better, improve readability, add proper documentation
   - For solutions: Structure the approach more clearly, break down complex steps, ensuring the format meets task requirements and can be correctly parsed

5. **Remove unnecessary elements**
   - Eliminate redundant or confusing parts
   - Streamline the prompt for clarity

6. **Add missing guidance**
   - Include any critical instructions that were missing
   - Add context that would help the agent perform better
</reasoning_rules>
"""

GRPO_OPTIMIZER_IMPROVEMENT_OUTPUT = """
<output>
CRITICAL: You MUST only improve variables that exist in <current_variables>. 
Use the EXACT variable names as shown in <current_variables> (e.g., "tool_context_rules", "reasoning_rules", "bash").
Do NOT invent new variable names or suggest new tools/variables that don't exist.

Please provide ONLY the improved variable content:
- For prompt variables: Provide the improved prompt text
- For tool variables: Provide the improved tool code (must be a valid Python class)
- For solution variables: Provide the improved solution approach
Do not include any additional commentary or explanation.
</output>
"""

GRPO_OPTIMIZER_IMPROVEMENT_SYSTEM_PROMPT_TEMPLATE = """
{{ agent_profile }}
{{ introduction }}
{{ reasoning_rules }}
{{ output }}
"""

GRPO_OPTIMIZER_IMPROVEMENT_AGENT_MESSAGE_PROMPT_TEMPLATE = """
{{ task }}
{{ current_variables }}
{{ reflection_analysis }}
"""

GRPO_OPTIMIZER_IMPROVEMENT_SYSTEM_PROMPT = {
    "name": "grpo_optimizer_improvement_system_prompt",
    "type": "system_prompt",
    "description": "System prompt for GRPO improvement optimizer",
    "template": GRPO_OPTIMIZER_IMPROVEMENT_SYSTEM_PROMPT_TEMPLATE,
    "variables": {
        "agent_profile": {
            "name": "agent_profile",
            "type": "system_prompt",
            "description": "Describes the agent's GRPO-guided optimization expertise.",
            "require_grad": False,
            "template": None,
            "variables": GRPO_OPTIMIZER_IMPROVEMENT_AGENT_PROFILE
        },
        "introduction": {
            "name": "introduction",
            "type": "system_prompt",
            "description": "Defines GRPO-guided optimization capabilities.",
            "require_grad": False,
            "template": None,
            "variables": GRPO_OPTIMIZER_IMPROVEMENT_INTRODUCTION
        },
        "reasoning_rules": {
            "name": "reasoning_rules",
            "type": "system_prompt",
            "description": "Defines how to use GRPO candidate analysis for optimization.",
            "require_grad": False,
            "template": None,
            "variables": GRPO_OPTIMIZER_IMPROVEMENT_REASONING_RULES
        },
        "output": {
            "name": "output",
            "type": "system_prompt",
            "description": "Defines the output format for GRPO-guided improvements.",
            "require_grad": False,
            "template": None,
            "variables": GRPO_OPTIMIZER_IMPROVEMENT_OUTPUT
        }
    }
}

GRPO_OPTIMIZER_IMPROVEMENT_AGENT_MESSAGE_PROMPT = {
    "name": "grpo_optimizer_improvement_agent_message_prompt",
    "type": "agent_message_prompt",
    "description": "Agent message for GRPO improvement optimizer",
    "require_grad": False,
    "template": GRPO_OPTIMIZER_IMPROVEMENT_AGENT_MESSAGE_PROMPT_TEMPLATE,
    "variables": {
        "task": {
            "name": "task",
            "type": "agent_message_prompt",
            "description": "Describes the task to be executed.",
            "require_grad": False,
            "template": None,
            "variables": None
        },
        "current_variables": {
            "name": "current_variables",
            "type": "agent_message_prompt",
            "description": "Describes the current variables that need to be improved.",
            "require_grad": False,
            "template": None,
            "variables": None
        },
        "reflection_analysis": {
            "name": "reflection_analysis",
            "type": "agent_message_prompt",
            "description": "Describes the GRPO candidate analysis for the current variables.",
            "require_grad": False,
            "template": None,
            "variables": None
        }
    }
}

@PROMPT.register_module(force=True)
class GrpoOptimizerImprovementSystemPrompt(Prompt):
    """System prompt template for GRPO improvement optimizer."""
    model_config = ConfigDict(arbitrary_types_allowed=True, extra="allow")

    type: str = Field(default='system_prompt', description="The type of the prompt")
    name: str = Field(default="grpo_optimizer_improvement", description="The name of the prompt")
    description: str = Field(default="System prompt for GRPO improvement optimizer", description="The description of the prompt")
    metadata: Dict[str, Any] = Field(default={}, description="The metadata of the prompt")

    prompt_config: Dict[str, Any] = Field(default=GRPO_OPTIMIZER_IMPROVEMENT_SYSTEM_PROMPT, description="System prompt information")

@PROMPT.register_module(force=True)
class GrpoOptimizerImprovementAgentMessagePrompt(Prompt):
    """Agent message prompt template for GRPO improvement optimizer."""
    model_config = ConfigDict(arbitrary_types_allowed=True, extra="allow")

    type: str = Field(default='agent_message_prompt', description="The type of the prompt")
    name: str = Field(default="grpo_optimizer_improvement", description="The name of the prompt")
    description: str = Field(default="Agent message prompt for GRPO improvement optimizer", description="The description of the prompt")
    metadata: Dict[str, Any] = Field(default={}, description="The metadata of the prompt")

    prompt_config: Dict[str, Any] = Field(default=GRPO_OPTIMIZER_IMPROVEMENT_AGENT_MESSAGE_PROMPT, description="Agent message prompt information")
