// Build the GA self-serve SPA into a CSP-safe static bundle at web/ga/.
//
// WHY this exists (and why it is NOT Vite): the design prototype
// (design/ga-selfserve/) is hand-authored *global-window* Babel-JSX — shell.jsx /
// screens.jsx have no ES imports/exports, they read window.AgentDexDesignSystem_*
// + window.GA and Object.assign(window, {...}). The live prototype compiles JSX
// in the BROWSER via @babel/standalone loaded from a CDN, which a strict
// production CSP (no unsafe-eval, no third-party script-src) blocks → /signup
// returns 200 but renders BLANK on the box. This build moves the JSX compile to
// BUILD time and vendors React locally so the served page is plain
// `<script src>`s of same-origin files: no eval, no CDN, no inline JS → renders
// under a strict `script-src 'self'` CSP.
//
// The output (web/ga/) is COMMITTED and shipped by the Dockerfile's `COPY web/`
// (design/ is NOT copied into the image, so a design-dir mount can never serve in
// prod). Regenerate after any design/ga-selfserve change:
//   cd tools/ga_spa && npm install && npm run build   (then commit web/ga/)
//
// The design files are READ-ONLY inputs here — the design lead owns design/**.

import babel from "@babel/core";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(HERE, "..", "..");
const SRC = path.join(REPO, "design", "ga-selfserve");
const DS = path.join(REPO, "design", "agentdex-design-system");
const NM = path.join(HERE, "node_modules");
const OUT = path.join(REPO, "web", "ga");
const APP = path.join(OUT, "app");

function log(...a) {
  console.log("[ga-spa]", ...a);
}

// ── clean + scaffold ──────────────────────────────────────────────────────────
fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(APP, { recursive: true });
fs.mkdirSync(path.join(OUT, "tokens"), { recursive: true });
fs.mkdirSync(path.join(OUT, "assets"), { recursive: true });

// ── 1. compile the global-JSX prototype at build time (classic runtime → global
//      React.createElement, exactly what the browser-Babel path produced) ───────
function compileJsx(name) {
  const code = fs.readFileSync(path.join(SRC, name), "utf8");
  const res = babel.transformSync(code, {
    filename: name,
    presets: [["@babel/preset-react", { runtime: "classic", development: false }]],
    babelrc: false,
    configFile: false,
    compact: false,
  });
  if (!res || !res.code) throw new Error(`babel produced no output for ${name}`);
  return res.code;
}
fs.writeFileSync(path.join(APP, "shell.js"), compileJsx("shell.jsx"));
fs.writeFileSync(path.join(APP, "screens.js"), compileJsx("screens.jsx"));
log("compiled shell.jsx + screens.jsx → app/{shell,screens}.js");

// ── 2. copy data + the prebuilt design-system component bundle ─────────────────
fs.copyFileSync(path.join(SRC, "data.js"), path.join(APP, "data.js"));
fs.copyFileSync(path.join(DS, "_ds_bundle.js"), path.join(APP, "ds-bundle.js"));

// ── 3. vendor React + ReactDOM (production UMD) — same origin, no CDN ──────────
fs.copyFileSync(
  path.join(NM, "react", "umd", "react.production.min.js"),
  path.join(APP, "react.production.min.js"),
);
fs.copyFileSync(
  path.join(NM, "react-dom", "umd", "react-dom.production.min.js"),
  path.join(APP, "react-dom.production.min.js"),
);
log("vendored react + react-dom (production UMD)");

// ── 4. boot: derive the screen from the URL path, then render the funnel ───────
//      External file (no inline <script>) so a strict `script-src 'self'` CSP
//      allows it. The prototype's FunnelApp reads location.hash for its initial
//      screen, so we map /signup|/login|/enroll|... → #screen before render —
//      no edit to the design source, no greedy client router needed.
const BOOT = `// generated by tools/ga_spa/build.mjs — do not edit
(function () {
  var SCREENS = ["signup", "login", "github", "enroll", "modes", "billing", "launch"];
  var seg = (location.pathname.match(/\\/(signup|login|github|enroll|modes|billing|launch)\\/?$/) || [])[1];
  if (seg && SCREENS.indexOf(seg) !== -1 && !location.hash) location.hash = "#" + seg;
  var root = document.getElementById("root");
  if (root && window.ReactDOM && window.React && window.FunnelApp) {
    window.ReactDOM.createRoot(root).render(window.React.createElement(window.FunnelApp));
  }
})();
`;
fs.writeFileSync(path.join(APP, "boot.js"), BOOT);

// ── 5. styles: the design-system manifest + its token tree (it @imports
//      ./tokens/*.css, so the relative tree must travel with it) ───────────────
fs.copyFileSync(path.join(DS, "styles.css"), path.join(OUT, "styles.css"));
for (const f of ["fonts.css", "colors.css", "typography.css", "spacing.css"]) {
  let css = fs.readFileSync(path.join(DS, "tokens", f), "utf8");
  if (f === "fonts.css") {
    // STRIP the Google Fonts @import: a third-party origin in the served bundle would
    // (a) beacon every /signup,/login,/enroll visitor's IP/UA to fonts.googleapis.com +
    // fonts.gstatic.com — a privacy leak on the passwordless sign-in surface — and
    // (b) be refused under the strict same-origin box CSP anyway. The typography tokens
    // carry full fallback stacks (system-ui / ui-monospace / Georgia / PingFang SC), so
    // the page renders fine without the webfonts. (Self-hosting the Latin faces for
    // brand fidelity is a follow-up; the CJK face — Noto Sans SC — is multi-MB to vendor.)
    const before = css;
    css = css.replace(/^\s*@import\s+url\(\s*['"]?https?:\/\/[^)]*\)\s*;?\s*$/gim, "");
    if (css === before) throw new Error("expected a remote @import to strip from fonts.css");
    css = "/* build.mjs stripped the Google Fonts @import — see web/ga build notes */\n" + css;
  }
  fs.writeFileSync(path.join(OUT, "tokens", f), css);
}
for (const f of ["agentdex-mark.svg", "agentdex-wordmark.svg"]) {
  fs.copyFileSync(path.join(DS, "assets", f), path.join(OUT, "assets", f));
}

// page chrome (was an inline <style> in the prototype; externalised so no inline
// style block is needed under a strict style-src).
const PAGE_CSS = `/* generated by tools/ga_spa/build.mjs — page chrome (prototype <style> block) */
html, body { margin: 0; min-height: 100%; }
body {
  background:
    radial-gradient(1100px 520px at 78% -8%, rgba(122,160,30,.10), transparent 60%),
    radial-gradient(820px 440px at 2% 2%, rgba(200,75,44,.06), transparent 55%),
    var(--bg);
  color: var(--ink); font-family: var(--font-display); font-size: 16px; line-height: 1.6;
  -webkit-font-smoothing: antialiased;
  transition: background var(--dur-3, 280ms) var(--ease-out, ease);
}
body[data-stage="arena"] {
  background: radial-gradient(1200px 600px at 80% -10%, #1a2030 0%, transparent 60%), var(--bg);
}
* { box-sizing: border-box; }
::selection { background: var(--lime-soft); }
[role="button"]:focus-visible, a:focus-visible, button:focus-visible, input:focus-visible {
  outline: 2px solid var(--accent-primary); outline-offset: 2px; border-radius: var(--r-xs);
}
/* no-JS fallback notice */
.ga-noscript {
  max-width: 560px; margin: 80px auto; padding: 28px 32px;
  font-family: var(--font-mono, monospace); font-size: 14px; line-height: 1.7; color: var(--ink, #222);
  border: 1px solid var(--border-default, #ccc); border-radius: 12px;
}
.ga-noscript a { color: var(--text-accent, #5a7a00); }
`;
fs.writeFileSync(path.join(OUT, "page.css"), PAGE_CSS);

// ── 6. the served shell — absolute /ga/ asset paths (path-agnostic so the same
//      file serves /signup, /login, /enroll), NO inline <script>/<style>, and a
//      <noscript> that names the passwordless auth surface (greppable auth hooks
//      + a structural no-password guarantee for the north-star probe). ─────────
const INDEX = `<!DOCTYPE html>
<html lang="en" data-theme="light">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="AgentDex GA self-serve — passwordless signup, GitHub device flow, email magic link.">
<meta name="agentdex:auth" content="passwordless; methods=github-device,email-magic-link; no-password">
<title>AgentDex · GA self-serve</title>
<link rel="stylesheet" href="/ga/styles.css">
<link rel="stylesheet" href="/ga/page.css">
</head>
<body>
<noscript>
  <div class="ga-noscript">
    <strong>AgentDex sign-in is passwordless.</strong>
    <p>We never use passwords. Continue with the <strong>GitHub device flow</strong>
    or an <strong>email magic link</strong> (ADR-0013). Please enable JavaScript to
    run the self-serve funnel, or use the CLI: <code>adx login</code>.</p>
  </div>
</noscript>
<div id="root"></div>
<script src="/ga/app/react.production.min.js"></script>
<script src="/ga/app/react-dom.production.min.js"></script>
<script src="/ga/app/ds-bundle.js"></script>
<script src="/ga/app/data.js"></script>
<script src="/ga/app/shell.js"></script>
<script src="/ga/app/screens.js"></script>
<script src="/ga/app/boot.js"></script>
</body>
</html>
`;
fs.writeFileSync(path.join(OUT, "index.html"), INDEX);

// ── guards (fail-closed: a future design change can't silently regress the floor) ──
// passwordless: neither the served HTML nor the compiled funnel may emit a password
// input. The compiled createElement props carry the input type, so scan them too —
// the static INDEX string alone would miss a JS-rendered field.
if (/type=["']?password/i.test(INDEX)) throw new Error("served HTML contains a password field");
for (const js of ["shell.js", "screens.js"]) {
  const src = fs.readFileSync(path.join(APP, js), "utf8");
  if (/type:\s*["']password["']/i.test(src) || /type=["']password/i.test(src)) {
    throw new Error(`compiled ${js} emits a password input (passwordless floor)`);
  }
}
// same-origin: the served CSS surface must carry NO third-party origin (no @import /
// url() to a remote host). SVG namespaces (w3.org) live only in the .svg assets and
// the React error-decoder URL only in the vendored min files — neither is CSS — so a
// blanket http(s) ban on the emitted CSS is precise and not brittle.
for (const css of ["styles.css", "page.css", "tokens/fonts.css", "tokens/colors.css", "tokens/typography.css", "tokens/spacing.css"]) {
  const src = fs.readFileSync(path.join(OUT, css), "utf8");
  if (/https?:\/\//i.test(src)) throw new Error(`third-party origin in emitted CSS ${css}`);
}

log("wrote web/ga/{index.html,page.css,styles.css,tokens/,assets/,app/}");
log("done.");
