// generated by tools/ga_spa/build.mjs — do not edit
(function () {
  var SCREENS = ["signup", "login", "github", "enroll", "modes", "billing", "launch"];
  var path = location.pathname.replace(/\/+$/, "");
  var seg = (path === "/arena" || path === "/battle/new")
    ? "modes"
    : ((path.match(/\/(signup|login|github|enroll|modes|billing|launch)$/) || [])[1]);
  if (seg && SCREENS.indexOf(seg) !== -1 && !location.hash) location.hash = "#" + seg;
  var root = document.getElementById("root");
  if (root && window.ReactDOM && window.React && window.FunnelApp) {
    window.ReactDOM.createRoot(root).render(window.React.createElement(window.FunnelApp));
  }
})();
