#!/usr/bin/env bash
# scripts/sync_toc.sh — keep TOC ("## Contents") in target markdown file fresh.
#
# Ported from ~/gh/eddie-agi-kb/scripts/sync_toc.sh (autonomous-pipeline mirror,
# 2026-06-09). CLAUDE.md line 7 already declares this script as the TOC
# generator; this file lands the declared behavior.
#
# Default target: CLAUDE.md at the project root.
# Override:  TARGET=/path/to/file.md bash scripts/sync_toc.sh
#
# Idempotent: if the existing Contents block matches the regenerated one, no
# write. Atomic write via tmp + mv. Exit 0 always — errors funnel to the
# monitor-gaps.md heartbeat log (per gap-log-review memory).

set -u
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET="${TARGET:-$REPO_ROOT/CLAUDE.md}"
GAP_LOG="${GAP_LOG:-$HOME/.cursor/projects/home-admin/heartbeat/monitor-gaps.md}"
TS="$(date -u +'%Y-%m-%d %H:%M:%S UTC')"

log_gap() {
  mkdir -p "$(dirname "$GAP_LOG")"
  printf '[%s] adx-cli sync_toc %s\n' "$TS" "$1" >>"$GAP_LOG"
}

if [ ! -f "$TARGET" ]; then
  log_gap "WARN target missing: $TARGET"
  exit 0
fi

# Build TOC body from all `## ` headings, skipping the Contents heading itself.
python3 - "$TARGET" <<'PY'
import re, sys, pathlib, os

target = pathlib.Path(sys.argv[1])
src = target.read_text(encoding="utf-8")

def anchor(t):
    # GitHub-style: lowercase, drop punct except spaces/hyphens, spaces→-, collapse.
    a = t.lower()
    a = re.sub(r"[^\w\s\-]", "", a)
    a = re.sub(r"\s+", "-", a.strip())
    a = re.sub(r"-+", "-", a)
    return a

# Skip frontmatter section if present (--- ... --- at top).
body = src
prefix = ""
m = re.match(r"^(---\n.*?\n---\n)", body, re.S)
if m:
    prefix = m.group(1)
    body = body[len(prefix):]

# Find all `## <heading>` (level 2 only).
headings = []
for ln in body.splitlines():
    m = re.match(r"^##\s+(.+?)\s*$", ln)
    if not m:
        continue
    h = m.group(1).strip()
    if h.lower() in ("contents", "table of contents", "toc"):
        continue
    headings.append(h)

toc_lines = ["## Contents", "", "_Auto-generated by scripts/sync_toc.sh; do not edit by hand._", ""]
for h in headings:
    toc_lines.append(f"- [{h}](#{anchor(h)})")
toc_lines.append("")
new_toc = "\n".join(toc_lines) + "\n"

# Strip any existing Contents block: from `## Contents` up to (but not including) the next `## `.
toc_re = re.compile(r"(?ms)^##\s+(?:Contents|Table of Contents|TOC)\s*\n.*?(?=^##\s|\Z)")
stripped = toc_re.sub("", body)

# Re-anchor: title line ends at first `## ` heading; TOC goes BEFORE that line.
# Title is `# <heading>` followed by any prose up to the first `## `.
parts = re.split(r"(?m)^(?=##\s)", stripped, maxsplit=1)
if len(parts) == 2:
    title_block, rest = parts
    title_block = title_block.rstrip() + "\n\n"
    new_body = title_block + new_toc + "\n" + rest
else:
    # No `## ` headings at all — nothing to TOC, no-op.
    new_body = stripped

new_full = prefix + new_body
if new_full == src:
    sys.exit(0)

tmp = target.with_suffix(target.suffix + ".tmp.sync_toc")
tmp.write_text(new_full, encoding="utf-8")
os.replace(tmp, target)
print(f"updated TOC in {target} ({len(headings)} sections)")
PY
